### PR TITLE
fix(tabs): always scroll active tab into view

### LINKED ISSUE #772: tabs: an active si-tab should always be visible tablist
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/element/blob/main/CONTRIBUTING.md).
- [x] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Affected component

<si-tab>

### Summary

An active si-tab is not automatically visible in the tablist when the consumer app set the input `active` to true on a tab which at the end of the list. Neither the drop-down show mark the active tab.
 

### Version

@siemens/element-ng@48.0.0

### Steps to reproduce

- create a list of si-tabs with 8 entries and show the label text
- set the last si-tab to active
- shrink the viewport size to a size where not all tabs are visible at once

### Code reproduction example

https://element.siemens.io/element-examples/#/overview/si-tabs/si-tabs

### What is the current bug behavior

The consumer app can't use the active input on si-tab to make a tab visible in the current list. At the moment this only happens when the user select an tab.

### What is the expected correct behavior

When the consumer app use the active input on si-tab we should ensure that the tab is visible in the current list.

### PR DESCRIPTION
**Pull request by chintankavathia**
Closes #772

- [x] I confirm that this MR follows the [contribution guidelines](https://github.com/siemens/element/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by spliffone — APPROVED** [review]
I love it and it works!

File: projects/element-ng/tabs/si-tabset.component.ts [hunk 1]
```diff
@@ -68,6 +69,21 @@ export class SiTabsetComponent {
     return tab instanceof SiTabLinkComponent;
   }
 
+  constructor() {
+    effect(() => {
+      if (this.activeTab()?.active() && this.showMenuButton()) {
```
Comment (spike-rabbit) [inline projects/element-ng/tabs/si-tabset.component.ts:74]:
```suggestion
      if (this.showMenuButton() && this.activeTab()) {
```

I think there is no need to check if the activeTab is active.
Switiching the order should ensure that the effect is triggered less often

**Review by spike-rabbit — CHANGES_REQUESTED** [review]
Please enhance the commit message. `on load` is not really the correct description.

File: projects/element-ng/tabs/si-tab-base.directive.ts
Comment (spike-rabbit) [inline projects/element-ng/tabs/si-tab-base.directive.ts:136]: I think you can make this a public method, and then the element itself can stay protected

**Review by spike-rabbit — CHANGES_REQUESTED** [review]
Found some more little thing

**Review by spike-rabbit — APPROVED** [review]
👍
